---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: symphony-kit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: symphony
  interval: 30s
  targetNamespace: symphony
  values:
    image: tag 2.9.9
    ingress:
      host: symphony..xip.io

